@startuml


class BufferReceiver{
    inbox: Message[]
    get(): Message
}

class BufferSender{
    outbox: Message[]
    put(): Message
}

abstract class Message{

}

abstract class Item
class Cola extends Item

class Player

abstract class Station
class SnackStation

class Counter

@enduml